#!/bin/sh -e

RED="\033[0;31m"	
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
CYAN="\033[0;36m"
RC="\033[0m"

gitpath="$HOME/.local/share" && mkdir -p "$gitpath"
confpath="$HOME/.config" && mkdir -p "$confpath"
